name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin
    - name: docker login
      run: docker build . --file .\docker\dockerfile --tag abmptit/docker-lab-static-website:${GITHUB_REF##*/} 
    - name: Build the Docker image
      run: docker build . --file .\docker\dockerfile --tag abmptit/docker-lab-static-website:${GITHUB_REF##*/} 
    - name: Push the Docker image
      run: docker push abmptit/docker-lab-static-website:${GITHUB_REF##*/} 
